#list of packages NFL
{ library("rvest")
  library("plyr")
  library("lubridate")
  library("rpart")
  library("rpart.plot")
  library("abind")
  library("rstudioapi")
  library("GMCM")
  library("glmnet")
  library("fitdistrplus")
  library("logspline")
  library("mice")
  library("VIM")
  library("lattice")
  library("gdata")
  library("missForest")
  library("rsample")
  library("purrr")
  library("vtreat")
  library("xgboost")
}